### ISSUE TITLE
How to deal with Vendor Attributes

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-cdb10#22]
Modify the ETS to handle situations where implementors do not have the Vendor_Attributes.xml files if there are no vendor attributes in the CDB.

**Comment by openfirmware** [comment]
I created a basic CDB based on the sample one in the ETS (`src/test/resources/CDB`) and removed its Vendor_Attributes XML and XSD files. The test suite still passes the CDB, is there another way this is causing a test failure?

**Comment by openfirmware** [comment]
Note: check emails for information on failing Vendor Attributes case

**Comment by openfirmware** [comment]
There are three cases that need to be reviewed regarding Vendor Attributes.

1. The CDB "Metadata" directory has no `vendor_attributes.xml` file present
2. There is a `vendor_attributes.xml` file, but it only has the base XML template and has no values
3. There is a `vendor_attributes.xml` file, and it has some values

Here is a sample XML template for the second case:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Vendor_Attributes
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.CDB-Spec.org/Schema/Version/3.2"
  xsi:schemaLocation="http://www.CDB-Spec.org/Schema/Version/3.2 Schema/Vendor_Attributes.xsd">
</Vendor_Attributes>
```

To resolve this issue, we need to review the test results for a sample CDB. Is there an example of vendor attributes that we can use? I don't see a complete example in the 1.0 specification.

**Comment by openfirmware** [comment]
I modified the CDB embedded in the tests suite for the various conditions.

* Test Case 1: No `vendor_attributes.xml` file present
    - All tests pass
* Test Case 2: `vendor_attributes.xml` with no child elements
    - One test fails: `vendor_attributes.xml` fails XML schema validation
* Test Case 3: `vendor_attributes.xml` with sample child elements (already present in sample CDB)
    - All tests pass

I checked into why Test Case 2 fails, and the [schema file](https://github.com/opengeospatial/ets-cdb10/blob/master/src/test/resources/CDB/Metadata/Schema/Vendor_Attributes.xsd) for `vendor_attributes` looks to be incomplete; it only allows child elements of `Example_Element_1` and `Example_Element_2`. This is exactly the sample contents of `vendor_attributes.xml`, which is why Test Case 3 passes.

I am guessing the sample XSD file was added until an official one was created. But the CDB specification and the sample files do not contain any Vendor Attributes schema files. @sarasaeedi , do you know if the schema for `vendor_attributes.xml` was finalized or published somewhere?

If not, we may have to add an XSD that is very permissive to pass any `vendor_attributes.xml` with unknown custom attributes.

**Comment by ghobona** [comment]
2020-08-26 team meeting.

The spec is contradictory in whether `Vendor_Attributes.xsd` or `Geomatics_Attributes.xsd` should be used. Therefore the test suite needs to exempt implementations from this requirement.

Also note that use of `Geomatics_Attributes.xml` is optional. So an implementation cannot be failed if the file is missing.

If the xml files exist, the test suite may validate them against the xsd files referenced in `schemaLocation`.

**Comment by ghobona** [comment]
2020-09-09

Discussion in the team meeting and agreement to prioritise this issue (https://github.com/opengeospatial/ets-cdb10/issues/22) over the zip issue (https://github.com/opengeospatial/ets-cdb10/issues/6)

**Comment by openfirmware** [comment]
I have a plan for implementation, which will add support for remote schemas for `Geomatics_Attributes.xml` and `Vendor_Attributes.xml`.

If the `schemaLocation` is an HTTP or HTTPS URL, then the remote file will be downloaded and used as the validation schema for the XML file. Errors will be raised if the file cannot be downloaded, or if the schema file is invalid.

If the `schemaLocation` is a relative URL, (e.g. `schemas/Geomatics_Attributes.xsd`) then that file will be used as the validation schema.

One issue is that some schemas in existing XML files may use the following host: [http://www.CDB-Spec.org/Schema/Version/3.2 Schema/Geomatics_Attributes.xsd](http://www.CDB-Spec.org/Schema/Version/3.2%20Schema/Geomatics_Attributes.xsd). This web host seems to be unreachable for me, so it may be an issue if it fails validation because the schema file cannot be downloaded. I am not sure if this file ever existed as we have not found an original copy of that XSD file. Anyone who gets this error due to using the "CDB-Spec.org" URL will have to switch to local paths for schema files or a publicly available web host.

Is having the test suite download a file over HTTP and use it for XML validation a security risk?

**Comment by ghobona** [comment]
Section 5.7.1.2.7.3 (page 229) says "There is one attribute metadata file (named CDB_Attributes.xml) that describes the CDB attributes of section 5.7.1.3, CDB Attributes, one attribute metadata file (named Geomatics_Attributes.xml) for the Geomatics attributes and one attribute metadata file (named Vendor_Attributes.xml) for the Vendor attributes. All three attribute metadata *.xml files are optional; if provided, they are included in the CDB folder hierarchy under the CDB Metadata directory (refer to section 3.1.1, Metadata Directory). All three attribute metadata *.xml files share the same schema. The schema that governs the contents of the attribute metadata files is Vector_Attributes.xsd."

**Comment by ghobona** [comment]
2020-09-23

@sarasaeedi To discuss this issue with the CDB SWG.

**Comment by ghobona** [comment]
Note that the XSD in schemas.opengis.net is different from the one in the test/resources example. 

http://schemas.opengis.net/cdb/1.0/Vector_Attributes.xsd

**Comment by ghobona** [comment]
2020-10-01

ETS development team agreed that given the contradiction in the spec, the resolution described at Comment https://github.com/opengeospatial/ets-cdb10/issues/22#issuecomment-680928671 still holds.
